# Generated by Django 5.0.6 on 2024-07-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_usuario_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='endereco',
        ),
        migrations.AddField(
            model_name='contato',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contato',
            name='cep',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contato',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contato',
            name='logradouro',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contato',
            name='uf',
            field=models.CharField(default='', max_length=2),
        ),
    ]
